### ISSUE TITLE
Class 'Recaptcha' not found

### ISSUE THREAD

**Issue by jonjie0317** [Waavi/recaptcha#4]
I followed the installation and set up, but when I rendered it in the view `{!! Recaptcha::render() !!}`  it returns an error says **Class 'Recaptcha' not found** . What happen to that?  Need help guys

**Comment by jonjie0317** [comment]
Thanks, but this package has no support.

**Comment by wojo0011** [comment]
try using a controller to load the view and importing the package class in the controller?
